Task: billtip
scorer: Birdbill
date: Jun30
multianimalproject: false
identity: false
project_path: D:\HBMR\dlc\billtip\billtip-HB-2026-06-30
engine: pytorch
video_sets:
  D:\HBMR\dlc\billtip\billtip-HB-2026-06-30\videos\20250704_174952_001-Percy-HBMR.mp4:
    crop: 0, 1280, 0, 720
  D:\HBMR\dlc\billtip\billtip-HB-2026-06-30\videos\20250704_175743_001-Pearl-HBMR.mp4:
    crop: 0, 1280, 0, 720
individuals:
- individual1
uniquebodyparts: []
multianimalbodyparts:
- bodypart1
- bodypart2
- bodypart3
bodyparts:
- bill_base
- bill_tip
start: 0
stop: 1
numframes2pick: 20
skeleton:
- - bodypart1
  - bodypart2
- - bodypart2
  - bodypart3
- - bodypart1
  - bodypart3
skeleton_color: black
pcutoff: 0.6
dotsize: 12
alphavalue: 0.7
colormap: rainbow
TrainingFraction:
- 0.95
iteration: 0
default_net_type: resnet_50
default_augmenter: albumentations
default_track_method: ellipse
snapshotindex: -1
detector_snapshotindex: -1
batch_size: 8
cropping: false
x1: 0
x2: 640
y1: 277
y2: 624
corner2move2:
- 50
- 50
move2corner: true
SuperAnimalConversionTables: null
detector_batch_size: 1
birdbill_labeled_data_folder: labeled-data/billtip
